package org.openidentity.core;

/** Stable machine-readable SDK/protocol failure codes. */
public enum OpenIdentityError {
  IDENTITY_MISMATCH,
  INVALID_SEQUENCE,
  INVALID_PREVIOUS_STATE_HASH,
  IDENTITY_NOT_ACTIVE,
  CONTROLLER_THRESHOLD_NOT_SATISFIED,
  DUPLICATE_VERIFICATION_METHOD,
  INVALID_POLICY_THRESHOLD,
  MISSING_PROOF_OF_POSSESSION,
  INVALID_PROOF_OF_POSSESSION,
  RECOVERY_NOT_CONFIGURED,
  INVALID_RECOVERY_POLICY,
  INVALID_RECOVERY_THRESHOLD,
  RECOVERY_THRESHOLD_NOT_SATISFIED,
  DUPLICATE_RECOVERY_PROOF,
  UNAUTHORIZED_RECOVERY_METHOD,
  INVALID_RECOVERY_SIGNATURE,
  INVALID_RECOVERY_COMMITMENT,
  INVALID_ISSUANCE_STATE_HASH,
  NO_ASSERTION_AUTHORITY,
  ASSERTION_THRESHOLD_NOT_SATISFIED,
  DUPLICATE_CREDENTIAL_PROOF,
  UNAUTHORIZED_CREDENTIAL_PROOF,
  INVALID_CREDENTIAL_SIGNATURE,
  INVALID_PROJECTED_CREDENTIAL,
  UNSUPPORTED_CREDENTIAL_PROFILE
}
